<?php
/**
 * ZF3 book MVC Skeleton Application
 *
 * @package    Application
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/mvc-skeleton-application
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
$this->h1('application_h1_index_index');

?>
<div class="row">
    <div class="col-md-3 col-sm-6">
        <h2>
            <i class="fa fa-question"></i>
            <?php echo $this->translate('application_h2_index_about'); ?>
        </h2>
        <p>
            <?php echo $this->translate('application_message_index_about'); ?>
        </p>
    </div>
    <div class="col-md-3 col-sm-6">
        <h2>
            <i class="fa fa-wrench"></i>
            <?php echo $this->translate('application_h2_index_features'); ?>
        </h2>
        <p>
            <?php echo $this->translate(
                'application_message_index_features'
            ); ?>
        </p>
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate(
                    'application_label_features_i18n'
                ) ?>
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate(
                    'application_label_features_layout'
                ) ?>
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate(
                    'application_label_features_session'
                ) ?>
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate(
                    'application_label_features_navigation'
                ) ?>
            </li>
        </ul>
    </div>
    <div class="col-md-3 col-sm-6">
        <h2>
            <i class="fa fa-cubes"></i>
            <?php echo $this->translate('application_h2_index_modules'); ?>
        </h2>
        <p>
            <?php echo $this->translate('application_message_index_modules'); ?>
        </p>
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate('application_label_modules_zdt') ?>
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate('application_label_modules_bp') ?>
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate('application_label_modules_sst') ?>
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate('application_label_modules_am') ?>
            </li>
        </ul>
    </div>
    <div class="col-md-3 col-sm-6">
        <h2>
            <i class="fa fa-desktop"></i>
            <?php echo $this->translate('application_h2_index_frontend'); ?>
        </h2>
        <p>
            <?php echo $this->translate(
                'application_message_index_frontend'
            ); ?>
        </p>
        <p></p>
        <ul class="fa-ul">
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate(
                    'application_label_frontend_bootstrap'
                ) ?>
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate(
                    'application_label_frontend_fontawesome'
                ) ?>
            </li>
            <li>
                <i class="fa-li fa fa-thumbs-up"></i>
                <?php echo $this->translate(
                    'application_label_frontend_jquery'
                ) ?>
            </li>
        </ul>
    </div>
</div>
